### PR TITLE
Vanilla tutorial

### PR DESCRIPTION
**Pull request by 9q9q**
Let me know what you think, if anything could be written better, etc. Will discuss with Bruno too.

### CODE REVIEW

**Comment by alvinz-matician** [comment]
The vis tools look really nice! Maybe we can put them into sparse coding/visualization for common use?

**Comment by 9q9q** [comment]
thanks! yeah i plan to add them to the library after submitting this and then will call those from this tutorial, but reviewers let me know if i should do that before submitting this.

**Comment by cshewmake2** [comment]
@9q9q this is amazing! Fantastic job. I'm definitely going to use these visualization methods!

**Review by cshewmake2 — APPROVED** [review]
Amazing! Let's get it in the main branch! ASAP

**Comment by alvinzz** [comment]
Some comments on the notebook:
 - It might be nice to motivate sparse coding (energy efficiency or in terms of computational principles).
 - Maybe re-title the "Learning Rule" section to "Learning the Basis Functions"?
   - Conceptually, it's similar to inferring the sparse code activations/coefficients, but the equations look different, so I feel that somebody without much background might find it confusing why that is.
 - Somewhere I think it would be nice to have a high-level explanation that we do this alternating optimization, where the basis functions are only updated after inferring the correct sparse coefficients.

**Pull request merged**
